version: "3"
services:
        
  demo:
    image: lucas2738/demo:0.0.2-SNAPSHOT
    volumes:
      - "../logs/demo/:/logs"
      - "./src/main/resources:/app/config"
    deploy:
      replicas: 1
    healthcheck:
      test: curl -f http://127.0.0.1:8080/actuator/health || exit 1
      interval: "60s"
      timeout: "10s"
      retries: 10
    ports:
      - "8081:8080"
    networks:
      demo-net:
        aliases:
         - demo-ms
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
    environment:
      - MYSQL_SERVER_ADDRESS=jdbc:mysql://mysql:3306/demo
      - POSTGRESSQL_SERVER_ADDRESS=r2dbc:postgresql://postgressql:5432/demo
      - POSTGRESSQL_SERVICE=postgressql
    depends_on:
      - mysql-server
      - postgressql-server
      - filebeat

networks:
  demo-net:
    driver: overlay