version: "3.2"
services:
      
  zookeeper:
    image: zookeeper:latest
    ports:
      - "2181:2181"
    deploy:
      replicas: 1

    networks:
      demo-net:

  kafka:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    ports:
      - target: 9093
        published: 9093
        protocol: tcp
        mode: global
    deploy:
      replicas: 1
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://kafka:9093
      #uncomment this line and comment the above one for launch demo and demo-client in debug. kafdrop will not work  
      #KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://:9092,OUTSIDE://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LOG_DIRS: /kafka/kafka-logs
      KAFKA_CREATE_TOPICS: "test:1:1,compact"
    #volumes:
    #  - ./k1-logs:/kafka/kafka-logs
    networks:
      demo-net:
      
  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - zookeeper
    ports:
       - "9094:9000"
    deploy:
      replicas: 1
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
      JVM_OPTS: "-Xms32M -Xmx64M"
      SERVER_SERVLET_CONTEXTPATH: "/"
    networks:
      demo-net:

networks:
  demo-net:
    driver: overlay
